#version: '3.8'

services:
  debtclear:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    container_name: debtclear-web
    restart: unless-stopped
    ports:
      - '3100:80'
    networks:
      - caddy-proxy # <-- Hubungkan ke jaringan caddy

networks:
  caddy-proxy:
    external: true
